eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: springcloud-eureka-client
#随机端口，后面复制这个项目，多启动几个实例
server:
  port: 0

management:
  server:
    port: 9090